/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExtensionLoginRouteImport } from './routes/extension/login'
import { Route as AuthSuccessRouteImport } from './routes/auth/success'
import { Route as AuthErrorRouteImport } from './routes/auth/error'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionLoginRoute = ExtensionLoginRouteImport.update({
  id: '/extension/login',
  path: '/extension/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSuccessRoute = AuthSuccessRouteImport.update({
  id: '/auth/success',
  path: '/auth/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/success': typeof AuthSuccessRoute
  '/extension/login': typeof ExtensionLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/success': typeof AuthSuccessRoute
  '/extension/login': typeof ExtensionLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/success': typeof AuthSuccessRoute
  '/extension/login': typeof ExtensionLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/auth/error'
    | '/auth/success'
    | '/extension/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/privacy' | '/auth/error' | '/auth/success' | '/extension/login'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/auth/error'
    | '/auth/success'
    | '/extension/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  AuthErrorRoute: typeof AuthErrorRoute
  AuthSuccessRoute: typeof AuthSuccessRoute
  ExtensionLoginRoute: typeof ExtensionLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension/login': {
      id: '/extension/login'
      path: '/extension/login'
      fullPath: '/extension/login'
      preLoaderRoute: typeof ExtensionLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/success': {
      id: '/auth/success'
      path: '/auth/success'
      fullPath: '/auth/success'
      preLoaderRoute: typeof AuthSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  AuthErrorRoute: AuthErrorRoute,
  AuthSuccessRoute: AuthSuccessRoute,
  ExtensionLoginRoute: ExtensionLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
